# Generated by Django 3.2.8 on 2021-10-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_commentaire_instagrameur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='commentateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagramapp.instagrameur'),
        ),
    ]
